
//movies
export const SET_MOVIES_POPULAR = "SET_MOVIES_POPULAR";
export const SET_MOVIES_NOW_PLAYING = "SET_MOVIES_NOW_PLAYING";
export const SET_MOVIES_TOP_RATED = "SET_MOVIES_TOP_RATED";
export const SET_MOVIES_UPCOMING = "SET_MOVIES_UPCOMING";

export const MOVIES_IS_LOADING = "MOVIES_IS_LOADING";