
//movies
export const SET_MOVIES_POPULAR = "SET_MOVIES_POPULAR";
export const SET_MOVIES_NOW_PLAYING = "SET_MOVIES_NOW_PLAYING";
export const SET_MOVIES_TOP_RATED = "SET_MOVIES_TOP_RATED";
export const SET_MOVIES_UPCOMING = "SET_MOVIES_UPCOMING";

export const MOVIES_IS_LOADING = "MOVIES_IS_LOADING";

//TV
export const SET_TV_ON_THE_AIR = "SET_TV_ON_THE_AIR";
export const SET_TV_AIRING_TODAY = "SET_TV_AIRING_TODAY";
export const SET_TV_TOP_RATED = "SET_TV_TOP_RATED";
export const SET_TV_POPULAR = "SET_TV_POPULAR";

export const TV_IS_LOADING = "TV_IS_LOADING";